import type { Post } from '../posts';

export const posts2: Post[] = [
  {
    slug: 'ci-cd-pipelines-explained',
    title: 'CI/CD Pipelines Explained: Ship Faster, Break Less',
    excerpt:
      'Continuous integration and deployment sound enterprise-y, but even solo developers benefit. Here is the practical version.',
    date: '2026-03-01',
    category: 'DevOps',
    readTime: 5,
    content: [
      'CI/CD is one of those terms that sounds heavier than it is. At its core, it means: every time you push code, machines automatically test it and (if it passes) deploy it. No manual uploads, no "did anyone run the tests?", no Friday-evening FTP roulette.',
      '## Continuous Integration',
      'CI is the habit of merging small changes often, with automated checks on every push — linting, type checks, tests, builds. The value is speed of feedback: you find out a change broke something minutes after writing it, while the context is fresh, instead of weeks later in production.',
      '## Continuous Deployment',
      'CD extends the pipeline to release automatically once checks pass. Modern platforms make this almost free: connect your GitHub repo to Vercel or a similar platform and every push to main deploys automatically, with preview deployments for every pull request.',
      '## A starter pipeline for any project',
      'Even a solo project deserves this minimum: a GitHub Actions workflow that installs dependencies, runs the linter and tests, and builds the app on every push. It takes twenty minutes to set up and permanently answers the question "is main branch healthy?"',
      'The deeper benefit is psychological. When deployment is automatic and reversible, releasing stops being an event and becomes routine. Small, frequent, boring deployments are how teams ship faster while breaking less.',
    ],
  },
  {
    slug: 'authentication-best-practices',
    title: 'Getting Authentication Right in Web Applications',
    excerpt:
      'Auth is where security mistakes hurt most. The core practices every developer should follow — and what to never build yourself.',
    date: '2026-02-22',
    category: 'Security',
    readTime: 6,
    content: [
      'Authentication is the front door of your application, and it is where mistakes cost the most. The good news: getting it right is mostly about following established practice instead of improvising.',
      '## Never store passwords — store hashes',
      'The cardinal rule: passwords are never stored, logged or emailed in plain text. They are hashed with an algorithm designed for passwords — bcrypt, scrypt or argon2 — which is deliberately slow to compute, making stolen databases expensive to crack. If your database leaks and you hashed properly, attackers get gibberish.',
      '## Sessions and tokens',
      'Whether you use server sessions or JWTs, the principles are the same: tokens should expire, be revocable where possible, and travel only over HTTPS. Store session tokens in httpOnly cookies rather than localStorage where practical — JavaScript that cannot read a token cannot leak it.',
      '## The features users deserve',
      'Rate-limit login attempts so bots cannot hammer your form. Offer two-factor authentication for anything valuable. Make password reset flows expire quickly and invalidate old links. And never reveal in error messages whether an email exists in your system — "invalid credentials" beats "wrong password for this account".',
      '## What not to build',
      'For most projects, do not hand-roll auth at all. Battle-tested options — established libraries and managed providers — have survived years of attacks that your custom implementation has not. Building your own auth system is a great learning exercise and a terrible production decision.',
      'Security is not a feature you add at the end; it is a set of defaults you start with.',
    ],
  },
  {
    slug: 'api-security-checklist',
    title: 'An API Security Checklist for Developers',
    excerpt:
      'The recurring vulnerabilities I see in real projects, and the straightforward defences that stop them.',
    date: '2026-02-15',
    category: 'Security',
    readTime: 6,
    content: [
      'Most API breaches are not sophisticated attacks — they are known weaknesses left unhandled. Here is the defensive checklist I run against every API I build or review.',
      '## Authenticate, then authorise',
      'Authentication asks "who are you?"; authorisation asks "are you allowed to do this?". The most common API vulnerability in real projects is missing the second check: an endpoint that verifies a user is logged in but never checks whether order 4521 actually belongs to them. Check object ownership on every request — never trust that the ID in the URL is one the caller should see.',
      '## Validate everything that comes in',
      'Treat every input — body, query params, headers — as hostile until validated. Use schema validation on request payloads, parameterised queries for every database call (SQL injection remains embarrassingly common), and reject unexpected fields rather than passing them through to your models.',
      '## Limit the blast radius',
      'Rate-limit endpoints so a single client cannot hammer your API. Return generic error messages to clients while logging details server-side — stack traces in API responses are free reconnaissance for attackers. Keep secrets in environment variables, never in code or version control, and rotate them if they ever leak.',
      '## The boring essentials',
      'HTTPS everywhere, dependencies updated (most exploits target known, already-patched vulnerabilities), CORS configured deliberately rather than set to allow everything, and audit logging on sensitive actions so you can answer "what happened?" after an incident.',
      'None of this is exotic. Consistent application of these basics puts your API ahead of the majority of what is running on the public internet.',
    ],
  },
  {
    slug: 'why-i-use-tailwind-css',
    title: 'Why I Use Tailwind CSS on Almost Every Project',
    excerpt:
      'Utility-first CSS looked ugly to me at first. Now it is the fastest way I know to build consistent, maintainable UIs.',
    date: '2026-02-08',
    category: 'Web Development',
    readTime: 5,
    content: [
      'My first reaction to Tailwind was the same as everyone\'s: "that HTML is hideous." A dozen class names on a single div felt like a step backwards from clean, semantic CSS. Then I built a project with it, and my objections evaporated one by one.',
      '## The problem it solves',
      'Traditional CSS grows without bound. Every feature adds new classes, nobody dares delete old ones, and eventually you have thousands of lines where changing anything might break something somewhere. Tailwind inverts this: styles live with the markup they affect, so deleting a component deletes its styles. There is no graveyard.',
      '## Speed and consistency',
      'The real productivity gain is never leaving your component file and never inventing names. No more pausing to decide between .card-inner-wrapper and .card-content-box. And because Tailwind\'s spacing, colours and type sizes come from a design scale, everything you build looks consistent by default — you pick from a palette instead of typing arbitrary pixel values.',
      '## Answering the classic objections',
      '"The HTML is unreadable" — you stop noticing within a week, and component frameworks like React mean you write those classes once per component, not per usage. "It\'s just inline styles" — it is not: you get hover and focus states, responsive breakpoints, and dark mode variants that inline styles cannot express.',
      '## Where I still write CSS',
      'Complex animations, unusual selectors, and genuinely reusable primitives still earn their own CSS. Tailwind is a default, not a religion. But for shipping professional UIs quickly — which is what clients pay for — nothing else I have used comes close.',
    ],
  },
  {
    slug: 'react-performance-tips',
    title: 'React Performance: Fix the Right Problems First',
    excerpt:
      'Most React "optimisation" advice targets problems you do not have. Here is where slowdowns actually come from.',
    date: '2026-02-01',
    category: 'JavaScript',
    readTime: 6,
    content: [
      'React performance advice online is dominated by memoisation trivia, but in real apps the biggest wins almost never come from useMemo. Here is where I actually find performance problems in client codebases.',
      '## Measure before touching anything',
      'The React DevTools Profiler shows you exactly which components render, how often and why. Ten minutes of profiling beats a day of speculative optimisation. Most apps have one or two genuinely hot spots — find them instead of sprinkling memo everywhere.',
      '## The usual suspects',
      'Rendering huge lists is the classic one: a table with two thousand rows does not need memoisation, it needs virtualisation — render only the rows on screen. State living too high in the tree is next: when typing in a search box re-renders the whole page, move that state closer to where it is used.',
      'Heavy computation inside render, effects that fetch in loops, and images without dimensions causing layout shifts round out the list. None of these are fixed by useCallback.',
      '## When memoisation does help',
      'React.memo, useMemo and useCallback earn their keep when an expensive subtree re-renders because of reference-unstable props, and profiling confirms it. Applied blindly, they add complexity and can even slow things down — every memo check is itself work.',
      '## Do not forget the network',
      'Perceived performance is often a data problem: waterfalls of sequential requests, no caching, refetching on every mount. Libraries like TanStack Query often improve "React performance" more than any render optimisation, because the bottleneck was never rendering.',
      'Fast apps come from architecture and measurement, not incantations.',
    ],
  },
  {
    slug: 'scaling-nodejs-applications',
    title: 'Scaling Node.js Applications: A Practical Path',
    excerpt:
      'From one process on one server to a system that handles real traffic — the stages, in order, without over-engineering.',
    date: '2026-01-25',
    category: 'Backend',
    readTime: 6,
    content: [
      'Scaling advice usually jumps straight to microservices and Kubernetes. For the vast majority of applications, the path is much more incremental — and most projects never need the later stages.',
      '## Stage one: do less work',
      'Before adding servers, stop wasting the one you have. Profile slow endpoints. Add database indexes for your real query patterns — a missing index is the number one cause of "Node is slow" complaints I investigate, and it is never Node. Cache expensive computations and hot queries with Redis. Move slow jobs (emails, PDFs, image processing) out of the request cycle into a background queue.',
      '## Stage two: use the whole machine',
      'Node runs on one CPU core by default. Cluster mode — via the built-in module or PM2 — runs one process per core, multiplying throughput on the hardware you already pay for. This requires your app to be stateless: sessions in Redis or JWTs, uploads to object storage, nothing important held in process memory.',
      '## Stage three: more machines',
      'Once stateless, horizontal scaling is straightforward: multiple servers behind a load balancer, health checks so bad instances drop out, and a database that has now become your real bottleneck — read replicas and connection pooling live here.',
      '## The honest ending',
      'Most applications live their entire lives happily in stages one and two. Distributed systems solve traffic problems most products never earn. Scale when metrics tell you to, not when conference talks do.',
    ],
  },
  {
    slug: 'building-admin-dashboards-clients-love',
    title: 'Building Admin Dashboards Clients Actually Use',
    excerpt:
      'Every business app needs an admin side. Here is what separates dashboards people love from ones they avoid.',
    date: '2026-01-18',
    category: 'Web Development',
    readTime: 5,
    content: [
      'Half of every business application is invisible to the public: the admin side where staff manage products, orders, users and content. It rarely gets design attention — and that is exactly why good admin UX is such a differentiator.',
      '## Design for the daily task, not the data model',
      'The lazy admin panel is a CRUD table for every database table. But admins do not think in tables; they think in tasks: "approve today\'s orders", "update this price", "find this customer\'s history". Start from the five actions staff perform most and make each one achievable in the fewest clicks possible. Everything else can live behind a search.',
      '## The features that earn gratitude',
      'Global search that actually works across records. Bulk actions — nobody wants to deactivate forty products one at a time. Sensible defaults and inline validation so mistakes are caught at entry. Activity logs answering "who changed this?" — the first question after every incident. And CSV export, because whatever your dashboard does, someone will still need it in a spreadsheet.',
      '## Roles matter early',
      'Even small teams need role separation: the intern updating product photos should not see revenue reports or be able to delete customers. Building roles in from the start is cheap; retrofitting them into a live system is painful.',
      '## Build or buy?',
      'Admin frameworks and headless CMS options cover standard needs quickly, and custom builds win when workflows are unusual. I often mix both: a CMS for content, custom screens for the workflows that make the business unique.',
    ],
  },
  {
    slug: 'progressive-web-apps-guide',
    title: 'Progressive Web Apps: The App Store Shortcut',
    excerpt:
      'PWAs give you offline support, home-screen installation and push notifications — without app store gatekeepers.',
    date: '2026-01-11',
    category: 'Mobile',
    readTime: 5,
    content: [
      'For many businesses that ask me for "an app", what they actually need is a Progressive Web App: a website with superpowers that installs to the home screen, works offline, and costs a fraction of native development.',
      '## What makes a PWA',
      'Three ingredients: HTTPS, a manifest file describing the app (name, icons, colours), and a service worker — a script that intercepts network requests and enables offline caching, background sync and push notifications. With these, browsers offer users the option to install your site like an app.',
      '## Why this matters in the Kenyan market',
      'Data costs and storage constraints are real here. A PWA is dramatically smaller than a typical native app download, updates instantly without app-store downloads, and its offline caching smooths over patchy connectivity. For users on budget Android phones with limited storage, "no 40MB download" is a genuine conversion advantage.',
      '## What PWAs do well — and where native still wins',
      'Content apps, e-commerce stores, dashboards, booking systems: PWAs handle these excellently. Native still wins for heavy device integration — advanced camera control, Bluetooth, background location — and for iOS push notification reliability, though Apple\'s support has improved substantially.',
      '## The strategy',
      'The pragmatic path I recommend to most clients: build a great responsive web app, add PWA capabilities for near-zero marginal cost, and only invest in native when a specific requirement demands it. Ship to every phone on earth today; visit the app stores when you have a reason to.',
    ],
  },
  {
    slug: 'finding-dropshipping-suppliers',
    title: 'Finding Reliable Dropshipping Suppliers: A Field Guide',
    excerpt:
      'Your supplier is your invisible business partner. How to find good ones, test them, and protect yourself from bad ones.',
    date: '2026-01-04',
    category: 'Dropshipping',
    readTime: 6,
    content: [
      'In dropshipping, your supplier ships the product, controls the quality and determines delivery speed — while your name takes the blame for their mistakes. Choosing suppliers is therefore not a checkbox; it is a core business decision.',
      '## Where to look',
      'AliExpress is where most beginners start: enormous selection, buyer protection, no minimums. Its weakness is inconsistent shipping and variable quality between sellers of identical items. Platforms like CJdropshipping and sourcing agents improve on this with faster lines, quality checks and custom packaging once you have consistent volume. The upgrade path matters more than the starting point.',
      '## How to evaluate any supplier',
      'Check their track record: store age, order volume, review trends over recent months (a good store gone recently bad shows up here). Message them before selling anything — response speed and clarity on a Tuesday afternoon predicts how they will handle your angry-customer crisis later.',
      'Then run the only test that counts: order the product yourself. You will learn the real shipping time, see the actual quality, and hold the packaging your customer will hold. Skipping this step to save $20 is how stores end up with 40% refund rates.',
      '## Protect yourself operationally',
      'Have a backup supplier identified for any product that starts scaling — suppliers run out of stock at the worst moments. Watch your first fifty orders closely for quality patterns. And build shipping time honestly into your product page; a customer told "12–20 days" is patient, a customer told nothing is a chargeback.',
      'Supplier sourcing and vetting is a full module in my dropshipping course, including the scripts I use for negotiating better prices at volume.',
    ],
  },
  {
    slug: 'branding-your-online-store',
    title: 'Branding Your Online Store: Beyond a Logo',
    excerpt:
      'Generic stores compete on price and lose. Branding is how small stores charge more and get remembered.',
    date: '2025-12-28',
    category: 'E-Commerce',
    readTime: 5,
    content: [
      'The difference between a store that survives and one that disappears is rarely the product — competitors can copy any product within weeks. What they cannot copy is a brand customers remember and trust.',
      '## Branding is a promise, not a logo',
      'A brand is the expectation a customer has before they open your package. It is built from every touchpoint: your store design, product photos, the tone of your emails, how fast support replies, what the unboxing feels like. A logo just labels that expectation.',
      '## The fundamentals for a small store',
      'Pick a specific customer and speak directly to them — a store for "everyone who likes gadgets" is a store for no one. Choose two or three colours and one or two fonts and use them with total consistency everywhere. Write product descriptions in a recognisable voice instead of pasting supplier text. Use consistent, high-quality photography — even good phone photos with clean backgrounds beat inconsistent supplier images.',
      '## Small signals, outsized trust',
      'A professional email address on your own domain. A real about page with a story and a face. Clear shipping and refund policies. Reviews with photos. Each one seems minor; together they are the difference between "random dropshipping site" and "small brand I feel okay giving my card details to".',
      '## Why this pays',
      'Branded stores get higher conversion rates, tolerate higher prices, win repeat customers and can build audiences on social media. Every shilling spent on branding lowers the cost of every future ad you run — it is infrastructure, not decoration.',
    ],
  },
  {
    slug: 'customer-service-for-dropshipping',
    title: 'Customer Service for Dropshipping: Your Real Moat',
    excerpt:
      'You cannot control the factory or the shipping line — but support is fully yours, and it decides your refund rate.',
    date: '2025-12-21',
    category: 'Dropshipping',
    readTime: 5,
    content: [
      'Dropshipping hands you a strange deal: you control the marketing and the storefront, but not the product quality or the delivery truck. Customer service is where you win back that control — and most dropshippers treat it as an afterthought.',
      '## Speed beats perfection',
      'A customer emailing "where is my order?" is not yet angry — they are nervous. A reply within a few hours, even one that just confirms the tracking status honestly, keeps them calm. The same message after four days of silence arrives at a chargeback. Set up templates for the ten questions you will receive constantly and answer everything within 24 hours, ideally much faster.',
      '## Design away the tickets',
      'The best support ticket is the one never sent. Show clear delivery estimates on the product page, send tracking automatically the moment it exists, and email proactively when something is delayed — customers forgive delays they were warned about and punish surprises. A good FAQ and order-tracking page removes half your inbox.',
      '## Refunds are marketing',
      'Fighting a $30 refund to lose a chargeback, a one-star review and a payment-processor strike is bad arithmetic. My rule: refund fast, refund politely, and study the pattern. If one product generates outsized complaints, the product is the problem — kill it regardless of its ad performance.',
      '## The compounding effect',
      'Stores with responsive support get fewer disputes, keep payment processors happy, collect better reviews and quietly build the repeat customers that make the economics work. Support is not a cost centre in this business; it is the moat.',
    ],
  },
  {
    slug: 'scaling-a-dropshipping-store',
    title: 'Scaling a Dropshipping Store Past Your First Wins',
    excerpt:
      'You found a winning product — now what? The playbook for scaling without watching profit evaporate.',
    date: '2025-12-14',
    category: 'Dropshipping',
    readTime: 6,
    content: [
      'Finding a winning product is the hard first milestone. Scaling it is a different skill — and the stage where profitable stores most often destroy themselves.',
      '## Scale spending gradually',
      'Ad platforms optimise around your budget; multiply it tenfold overnight and performance usually collapses. Increase budgets in steady steps every few days, watching cost per purchase at each level, and duplicate winning campaigns into new audiences and new creative angles rather than piling everything on one campaign.',
      '## Fix operations before they break you',
      'Volume exposes every weak link. Talk to your supplier before scaling — confirm stock depth and negotiate pricing at volume, because per-unit discounts at scale go straight to profit. Line up a backup supplier now, not during the stockout. If order processing is manual, automate it before order volume makes you a bottleneck in your own business.',
      '## Diversify deliberately',
      'A store scaling on one product and one ad platform is one policy change away from zero. Add complementary products your existing customers would want — upsells and bundles raise average order value, which is often easier than lowering ad costs. Expand to a second traffic channel once the first is stable, and start collecting emails from day one: your list is the only audience no algorithm can take away.',
      '## Watch real profit, not revenue',
      'Scaling stores drown in screenshots of revenue dashboards while margins quietly die. Track net profit weekly — after ads, fees, refunds and product costs. Revenue is vanity; margin is the business.',
    ],
  },
  {
    slug: 'email-marketing-for-ecommerce',
    title: 'Email Marketing for E-Commerce: The Channel You Own',
    excerpt:
      'Ads rent attention; email owns it. The flows and campaigns that quietly drive a third of mature store revenue.',
    date: '2025-12-07',
    category: 'Marketing',
    readTime: 6,
    content: [
      'Every ad platform can raise prices or ban your account tomorrow. Your email list is the only marketing asset you fully own — and for mature e-commerce stores, it routinely drives a large share of revenue at almost no marginal cost.',
      '## Automated flows: set once, earn always',
      'Flows are triggered sequences that run themselves. Four matter most. The welcome flow greets new subscribers, tells your story and usually delivers a first-purchase incentive — it will be your highest-converting email forever. The abandoned-cart flow recovers shoppers who left at checkout; with meaningful percentages of carts abandoned, this sequence is found money. Post-purchase flows confirm, reassure and set up the review request. Win-back flows re-engage customers who have gone quiet.',
      '## Growing the list',
      'Offer something real for the signup — a discount, early access, genuinely useful content. Popups work when timed politely (exit intent, or after genuine browsing, not instantly on arrival). Every checkout should feed the list.',
      '## Campaigns without burnout',
      'Beyond automation, send regular campaigns: new arrivals, honest promotions, content your audience actually enjoys. The discipline is consistency over cleverness — a plain weekly email beats a brilliant quarterly one. Write like a person, keep one clear call to action, and always send from a name, not a brand robot.',
      '## The metric that matters',
      'Watch revenue per email sent, not open rates. And prune subscribers who never engage — a smaller, warmer list delivers better inbox placement than a big dead one.',
    ],
  },
  {
    slug: 'google-ads-vs-facebook-ads',
    title: 'Google Ads vs Facebook Ads: Intent vs Discovery',
    excerpt:
      'The two ad giants do fundamentally different jobs. Knowing which job you need is most of the decision.',
    date: '2025-11-30',
    category: 'Marketing',
    readTime: 5,
    content: [
      'Businesses constantly ask me whether to spend on Google or Facebook. The honest answer: they are not competitors so much as different tools. One captures demand; the other creates it.',
      '## Google: harvesting intent',
      'Google Ads intercepts people actively searching for what you sell. Someone typing "emergency plumber Nairobi" or "buy standing desk Kenya" has raised their hand — your ad just needs to be there with a credible offer. Search campaigns convert at high rates because the customer arrived pre-sold on the category; you are only competing on choice of provider.',
      'This makes Google the natural home for services, local businesses, and products people already know they want. Its limit: volume is capped by how many people are searching. You cannot harvest demand that does not exist.',
      '## Facebook and Instagram: creating discovery',
      'Meta ads interrupt people who were not shopping at all — which sounds worse, but is exactly how impulse products, new brands and "I didn\'t know this existed" purchases work. With strong creative, Meta manufactures demand at enormous scale. That is why it dominates dropshipping and consumer product launches.',
      'The trade: you pay for the persuasion. Creative quality determines everything, and costs rise when your ads fatigue.',
      '## The practical playbook',
      'Selling something people search for? Start with Google. Selling something people discover? Start with Meta. Have budget for both? Use Meta to create demand and Google brand-and-search campaigns to catch the people who saw your ad and searched for you an hour later — the combination consistently outperforms either alone.',
    ],
  },
  {
    slug: 'payment-gateways-in-kenya',
    title: 'Payment Gateways in Kenya: What to Offer Your Customers',
    excerpt:
      'M-Pesa, cards, PayPal and more — how to choose payment options that match how Kenyans actually pay.',
    date: '2025-11-23',
    category: 'E-Commerce',
    readTime: 6,
    content: [
      'A checkout that does not match how your customers pay is a leaky bucket — everything you spent getting them there drains out at the final step. In Kenya, payment strategy starts with one obvious fact and gets more interesting from there.',
      '## M-Pesa first, always',
      'For Kenyan customers, M-Pesa is not a payment option; it is the payment default. Offering STK Push — where the customer receives a PIN prompt on their phone at checkout — dramatically outperforms asking them to send money manually to a Paybill and type a confirmation code. The integration effort pays for itself in completed checkouts.',
      '## Cards and the gateways that bundle everything',
      'Card payments matter for corporate customers, the diaspora and international buyers. In practice, most Kenyan businesses are best served by an aggregator that bundles M-Pesa, cards and sometimes bank transfers behind one integration and one settlement flow — Pesapal, Flutterwave, DPO and IntaSend are the names that come up in most of my client conversations. Compare their transaction fees, settlement speed and developer experience for your specific volume; the differences are real.',
      '## Selling beyond Kenya',
      'International customers expect familiar options: Stripe and PayPal dominate expectations. Stripe\'s Kenya availability has historically been limited, which is why many Kenyan founders selling globally route through platforms or international-friendly processors. If your dropshipping store targets the US or Europe, set this up properly from day one — payment friction kills foreign trust instantly.',
      '## Checkout principles',
      'Show prices in the customer\'s currency, display all fees before the final step, and confirm payment on screen and by message immediately. Every second of ambiguity after someone pays is trust burning.',
    ],
  },
  {
    slug: 'remote-work-as-a-kenyan-developer',
    title: 'Landing Remote Work as a Kenyan Developer',
    excerpt:
      'Remote work turned geography from a ceiling into a detail. How Kenyan developers actually land international roles.',
    date: '2025-11-16',
    category: 'Career',
    readTime: 6,
    content: [
      'The best thing that happened to African developers in the last decade is that the world went remote and never fully went back. Kenyan developers now compete for — and win — roles paying international rates from Nairobi, Kisumu and everywhere between. Here is what actually moves the needle.',
      '## Make yourself findable and verifiable',
      'International employers hire against risk. Everything public about you either raises or lowers their perceived risk: a GitHub with real projects and readable code, a portfolio site that loads fast and explains what you built, a LinkedIn that says clearly what you do. Verifiable beats impressive — three deployed projects with live links outweigh a CV full of adjectives.',
      '## Where the jobs are',
      'Dedicated remote boards (and the remote filters on major job sites) list thousands of roles, but referrals still convert best — which makes community participation practical career strategy, not networking theatre. Contribute to open source, be helpful in developer communities, post what you learn. Opportunities follow visibility.',
      '## Interview realities',
      'Expect timezone questions — have a clear answer about your working hours and overlap. Expect communication to be weighted as heavily as code; remote teams run on writing, so clear written English in your application is itself a technical signal. And test your setup: reliable internet and power backup are part of your professional infrastructure here, not optional extras.',
      '## Getting paid',
      'Learn the payment landscape before you need it — international platforms, USD accounts and their fees. Understand your KRA obligations as a freelancer or contractor early; clean finances make you calmer in negotiations.',
      'The ceiling for Kenyan developers has never been higher. The work is real, but the path is proven.',
    ],
  },
  {
    slug: 'learning-to-code-in-2026-roadmap',
    title: 'Learning to Code in 2026: A Realistic Roadmap',
    excerpt:
      'Forget the 30-day promises. Here is an honest path from zero to employable developer, including the AI question.',
    date: '2025-11-09',
    category: 'Career',
    readTime: 7,
    content: [
      'People regularly ask me how to start coding, usually braced for a complicated answer. The path is actually simple — just not fast. Here is the roadmap I give, updated for a world where AI writes code too.',
      '## Phase one: web fundamentals',
      'Start with HTML, CSS and JavaScript — not because web is the only path, but because feedback is instant and visible, and motivation feeds on visible progress. Build small real things immediately: a personal page, a calculator, a to-do list. Typing code you understand beats watching tutorials you almost understand. Aim for a few months of consistent practice, even an hour a day.',
      '## Phase two: depth and a framework',
      'Go deeper into JavaScript — functions, arrays, objects, async — until reading code feels like reading. Then learn React, learn Git properly, and touch a backend (Node.js keeps you in one language). Build projects that talk to real APIs and store real data.',
      '## Phase three: proof',
      'Employability is proof of work. Build two or three substantial projects, deploy them live, write clean READMEs. A portfolio site with deployed, clickable work moves more interviews than any certificate.',
      '## The AI question',
      'Should you still learn to code when AI writes code? Yes — emphatically. AI tools make skilled developers dramatically faster, but they amplify judgment rather than replace it. Someone who cannot read code cannot verify, debug or direct what AI produces. Learn fundamentals deeply, use AI as an accelerator from day one, and you graduate into the most leveraged generation of developers yet.',
      '## The only real requirement',
      'Consistency beats intensity. An hour daily for a year beats every bootcamp weekend binge. Start today, stay boringly consistent, and eighteen months from now you will be answering these questions for someone else.',
    ],
  },
];
