import type { Post } from '../posts';

export const posts3: Post[] = [
  {
    slug: 'developer-portfolio-tips',
    title: 'Building a Developer Portfolio That Gets You Hired',
    excerpt:
      'Most portfolios list technologies. The ones that win work tell stories about problems solved. Here is the difference.',
    date: '2025-11-02',
    category: 'Career',
    readTime: 5,
    content: [
      'I have reviewed dozens of developer portfolios, and the pattern is consistent: most read like inventory lists — "React, Node, MongoDB" — while the ones that land interviews read like case studies.',
      '## Show outcomes, not stacks',
      'For each project, answer three questions: what problem did this solve, what did you build, and what happened as a result? "Built a booking system that cut a clinic\'s phone scheduling by 80%" beats "Full-stack app with React frontend and Express backend" every single time. Recruiters and clients hire outcomes; the stack is a footnote.',
      '## Three good projects beat ten tutorials',
      'Everyone can spot a tutorial project — another weather app, another movie database clone. One original project you conceived, built and deployed says more than ten follow-alongs. It shows you can navigate ambiguity, which is the actual job.',
      '## Make everything clickable and alive',
      'Deploy your projects. Dead GitHub links and "demo coming soon" undermine everything. A live URL that loads fast on a phone is proof; a repository alone is a promise. And your portfolio site itself is exhibit one — if it is slow, broken on mobile or last touched in 2023, that is your work sample.',
      '## Lower the effort to contact you',
      'End every page with an obvious next step: email, WhatsApp, calendar link. I have won projects simply because I was the easiest qualified person to reach. Your portfolio has one job — starting conversations. Design for that.',
    ],
  },
  {
    slug: 'clean-code-habits',
    title: 'Clean Code Habits That Compound Over a Career',
    excerpt:
      'Clean code is not aesthetics — it is economics. The habits that keep codebases changeable years after they ship.',
    date: '2025-10-26',
    category: 'Web Development',
    readTime: 6,
    content: [
      'Every codebase I have inherited taught me the same lesson: code is read far more often than it is written, and the true cost of messy code arrives months later, paid by whoever touches it next — usually you.',
      '## Name things like you mean it',
      'Naming is the highest-leverage clean-code habit. A variable called daysUntilExpiry needs no comment; one called d needs a paragraph. If you struggle to name a function, that struggle is information — the function probably does too many things to have one name.',
      '## Small functions, honest functions',
      'A function should do what its name says, all of what its name says, and nothing else. When a function named sendInvoice also updates inventory and logs analytics, every future reader gets ambushed. Splitting logic into small, single-purpose functions makes code testable, reusable and — most importantly — skimmable.',
      '## Comments explain why, code explains what',
      'Delete comments that narrate the code ("increment counter"). Keep comments that explain what code cannot say: why this weird workaround exists, why this order of operations matters, which bug this guards against. Then let clear names and structure do the rest.',
      '## Leave it slightly better',
      'The boy-scout rule — leave code cleaner than you found it — compounds like interest. Rename one bad variable, extract one tangled block, delete one dead function per visit. No heroic rewrite required; a codebase touched this way gets healthier every sprint instead of sicker.',
      'Clean code is a kindness to your future self, disguised as discipline.',
    ],
  },
  {
    slug: 'git-workflow-for-teams',
    title: 'A Git Workflow That Keeps Teams Sane',
    excerpt:
      'Branches, pull requests and commit hygiene — the simple conventions that prevent most collaboration pain.',
    date: '2025-10-19',
    category: 'DevOps',
    readTime: 5,
    content: [
      'Git problems are rarely Git problems — they are workflow problems. Teams that agree on a few simple conventions almost never hit the merge disasters that plague teams that "just push".',
      '## The branch rules',
      'Main stays deployable, always. All work happens on short-lived branches named for what they do — feature/mpesa-checkout, fix/login-redirect — and merges back through pull requests. The key word is short-lived: a branch that lives for three weeks is a merge conflict with a countdown timer. Small branches merged frequently beat big branches merged painfully.',
      '## Commits that tell a story',
      'Write commit messages for the person running git log during an outage at 2am — that person is future you. "Fix cart total rounding for KES amounts" helps; "fixes", "wip" and "final final" do not. Commit logical units, not end-of-day snapshots: each commit should represent one coherent change that could be understood, or reverted, on its own.',
      '## Pull requests as quality gates',
      'Even on a two-person team, PRs earn their overhead: a second pair of eyes catches bugs cheaply, knowledge spreads instead of siloing, and CI gets a natural place to run tests before anything touches main. Keep PRs small enough to review properly — a 2,000-line PR gets approved on faith, which means it was not reviewed at all.',
      '## When things go wrong',
      'Learn git revert for undoing safely on shared branches, and reserve rebase and force-push for branches only you touch. Most Git horror stories start with someone rewriting shared history to make the log look prettier.',
    ],
  },
  {
    slug: 'testing-strategies-for-web-apps',
    title: 'Testing Web Apps: What to Test and What to Skip',
    excerpt:
      'One hundred percent coverage is a vanity metric. Here is where tests actually pay their rent.',
    date: '2025-10-12',
    category: 'Web Development',
    readTime: 6,
    content: [
      'Testing advice tends to come in two useless flavours: "test everything" and silence. Real projects have limited hours, so the useful question is where tests deliver the most protection per minute spent writing them.',
      '## Test money paths first',
      'Start where bugs cost the most: checkout, payments, authentication, anything that changes account state. A bug in a marketing page embarrasses you; a bug in payment processing costs revenue and trust. These flows deserve tests before anything else in the codebase.',
      '## The practical pyramid',
      'Unit tests cover pure logic — price calculations, validators, data transformations — and run in milliseconds. Integration tests verify your API endpoints against a real test database: does POST /orders actually create an order, reject bad input, enforce ownership? A handful of end-to-end tests then walk the critical user journeys in a real browser. Many fast unit tests, a solid layer of integration tests, few E2E tests — that ratio keeps suites fast enough that people actually run them.',
      '## What to skip',
      'Testing implementation details (which internal function called which) makes refactoring miserable while catching nothing users care about. Snapshot-testing entire pages produces tests that fail on every change and get blindly re-approved. And chasing coverage percentages produces tests that execute code without asserting anything meaningful.',
      '## The regression habit',
      'Every production bug gets a test that reproduces it before the fix. This single discipline — cheap, automatic, cumulative — guarantees the same bug never ships twice, and quietly builds your suite around the failures your app actually has rather than the ones you imagined.',
    ],
  },
  {
    slug: 'ai-tools-in-my-developer-workflow',
    title: 'How AI Tools Fit Into My Development Workflow',
    excerpt:
      'AI coding assistants made me faster — but not in the ways I expected. An honest account from daily use.',
    date: '2025-10-05',
    category: 'AI & Tools',
    readTime: 6,
    content: [
      'I use AI coding tools daily, and the honest summary is: transformative for some work, marginal for other work, and dangerous exactly when you stop paying attention.',
      '## Where AI genuinely accelerates me',
      'Boilerplate and scaffolding — CRUD endpoints, form validation, config files — where the shape is known and typing is the bottleneck. Unfamiliar territory, where asking "how do I do X in this framework" beats twenty minutes of documentation spelunking. Debugging, where pasting an error and context often surfaces the cause instantly. And test writing, where AI drafts the tedious cases and I sharpen the assertions.',
      '## Where it still needs me',
      'Architecture decisions, because AI happily generates confident code for the wrong design. Business logic unique to a client, which no model has seen before. And anything security-sensitive, where plausible-looking code can hide subtle holes. AI output is a draft from a fast, well-read junior — useful precisely in proportion to how carefully it gets reviewed.',
      '## The discipline that makes it safe',
      'Never merge code you could not explain line by line. Read AI code with more suspicion than your own, not less — it is fluent, which disguises its errors. And keep writing some code unassisted; the judgment you need to supervise AI comes from the practice AI tempts you to skip.',
      '## For newer developers',
      'Use AI to learn faster, not to skip learning: ask it to explain, compare approaches, review your code. The developers who thrive in this era are the ones whose fundamentals let them command the tools rather than trust them blindly.',
    ],
  },
  {
    slug: 'building-a-saas-in-kenya',
    title: 'Building a SaaS Product in Kenya: Lessons and Realities',
    excerpt:
      'Software subscriptions meet Kenyan market realities — pricing, payments, and picking problems worth solving.',
    date: '2025-09-28',
    category: 'Business',
    readTime: 6,
    content: [
      'Every developer eventually dreams of it: build software once, charge monthly, sleep while revenue accrues. SaaS is a real path — including from Kenya — but the local realities reshape the playbook in ways worth knowing before you write code.',
      '## Pick a problem with a budget attached',
      'The classic mistake is building for users who cannot pay. A brilliant app for matatu commuters faces brutal monetisation; boring software that saves SMEs money — invoicing, inventory, payroll compliance, school fee management — meets customers who already spend to solve these problems. In B2B, "who pays and why" should be answerable in one sentence before any code exists.',
      '## Price for the market, collect like the market',
      'Kenyan SMEs think in monthly cash flow, and M-Pesa recurring collection is your friend — invoice-plus-STK-push or paybill standing arrangements work where card-on-file subscriptions stumble. Annual discounts convert surprisingly well when framed as savings. And consider USD pricing for any product that can serve customers beyond Kenya; the same code sells at very different price points across borders.',
      '## Distribution beats features',
      'Local SaaS wins through trust channels: industry associations, accountants who recommend tools to all their clients, WhatsApp groups where your target trade actually talks. A mediocre product with a distribution partner outsells a beautiful one waiting to be discovered.',
      '## Start embarrassingly small',
      'Launch with one workflow done excellently, onboard your first ten customers personally, and let their complaints write your roadmap. SaaS compounds slowly — the founders who win are the ones still improving the product in year three, after the excitement is gone.',
    ],
  },
  {
    slug: 'landing-pages-that-convert',
    title: 'Landing Pages That Convert: Structure Over Cleverness',
    excerpt:
      'A landing page has one job. The proven structure that turns visitors into leads, and the mistakes that quietly kill conversion.',
    date: '2025-09-21',
    category: 'Marketing',
    readTime: 5,
    content: [
      'A landing page is a salesperson that never sleeps — and most of them are terrible at their job, not because of bad design, but because of unclear thinking about the one action the page exists to produce.',
      '## The five-second test',
      'A stranger landing on your page should answer three questions within five seconds: what is this, who is it for, and what do I do next? Clever headlines lose to clear ones every time. "Get a professional website for your business in 14 days" outperforms "Digital experiences, reimagined" — the first tells; the second decorates.',
      '## The structure that works',
      'Headline stating the outcome. Subheadline handling the obvious objection. One clear call to action, repeated down the page. Social proof — testimonials with names and faces, client logos, real numbers. Benefits framed as outcomes ("save ten hours a week"), features as supporting evidence. A short FAQ that pre-empts the hesitations you hear on sales calls. Then the call to action again.',
      '## The conversion killers',
      'Multiple competing actions — a page asking visitors to buy, subscribe, follow and download converts on none of them. Slow load times, especially on mobile where most Kenyan traffic lives. Forms demanding ten fields when a name and phone number would do. And burying the call to action below walls of text nobody scrolls through.',
      '## Iterate with evidence',
      'Ship, measure, adjust: watch where visitors drop, test one change at a time — headline first, it carries the most weight. Conversion is a process, not a launch-day property.',
    ],
  },
  {
    slug: 'website-maintenance-guide',
    title: 'Website Maintenance: The Ownership Manual Nobody Gives You',
    excerpt:
      'Websites are not fire-and-forget. The monthly habits that prevent hacks, downtime and slow decay.',
    date: '2025-09-14',
    category: 'Web Development',
    readTime: 5,
    content: [
      'Businesses budget for building a website and almost never for keeping it alive. Then two years later the site is slow, hacked or silently broken on new phones — and the rebuild costs more than maintenance ever would have.',
      '## What decays and why',
      'Software rots by standing still: dependencies accumulate known vulnerabilities, plugins fall out of compatibility, SSL certificates expire, and forms quietly stop delivering email when a provider changes policy. None of this announces itself — you discover it when a customer mentions your contact form has been dead for months.',
      '## The monthly checklist',
      'Update the platform, plugins and dependencies. Verify backups exist and — the step everyone skips — that they actually restore. Click through your critical paths by hand: forms, checkout, login. Check speed with PageSpeed Insights and scan Search Console for errors and warnings. Thirty minutes monthly prevents most disasters.',
      '## Security basics that stop real attacks',
      'Most compromised small-business sites fall to boring causes: outdated software with known exploits, weak admin passwords, no login protection. Updates, strong unique passwords with two-factor authentication, and a firewall service like Cloudflare in front of the site stop the automated attacks that make up nearly all real-world threat volume.',
      '## Budget for it like insurance',
      'Whether you handle it internally or pay a maintenance retainer, the arithmetic is simple: steady small upkeep costs a fraction of one emergency rebuild or one weekend of a hacked site emailing your customers. I offer maintenance plans on every site I build for exactly this reason.',
    ],
  },
  {
    slug: 'domains-and-hosting-explained',
    title: 'Domains and Hosting Explained for Non-Developers',
    excerpt:
      'What you are actually buying when you buy a website — domains, hosting, SSL and DNS in plain language.',
    date: '2025-09-07',
    category: 'Web Development',
    readTime: 5,
    content: [
      'Clients sign up for domains and hosting every day without anyone explaining what they bought. Here is the plain-language version I give every client — worth understanding, because these accounts are business assets you should control.',
      '## The domain is your address',
      'A domain (like mjtechlabs.me) is a rented name pointing to your website — renewed yearly, and lost if you forget. Register it yourself, in your own account, with your own email. The saddest recurring story in this industry is a business locked out of its own name because a long-gone freelancer or agency registered it under theirs.',
      '## Hosting is the building',
      'Hosting is the computer that stores your site and serves it to visitors. Shared hosting is cheap and fine for simple sites; cloud platforms like Vercel deploy modern sites globally, often free at small scale; VPS servers offer power for those who can administer them. The right answer depends on what your site is built with — which is why hosting should be chosen after the technology, not before.',
      '## The supporting cast',
      'DNS is the phonebook connecting your name to your hosting — change hosts and only the DNS record needs updating. SSL is the padlock in the browser: it encrypts traffic, and it is free and automatic on modern platforms, so never pay extra for basic certificates. Professional email (you@yourbusiness.co.ke) is a separate service — Google Workspace or Zoho — not something that magically comes with the domain.',
      '## The ownership rule',
      'Whoever controls the domain account and hosting account controls the business asset. Keep both registered to you, pay for them directly, and grant your developer access — never the reverse.',
    ],
  },
  {
    slug: 'ux-mistakes-that-cost-sales',
    title: 'UX Mistakes That Quietly Cost You Sales',
    excerpt:
      'Users rarely report bad UX — they just leave. The most common conversion killers I find in site audits.',
    date: '2025-08-31',
    category: 'Web Development',
    readTime: 5,
    content: [
      'When sales are low, businesses blame the product or the traffic. But auditing their websites usually reveals a third culprit: friction. Users do not file complaints about bad UX — they close the tab. Here are the killers I find over and over.',
      '## Making people think',
      'Every moment of confusion taxes conversion: navigation labels only insiders understand, prices hidden behind "contact us", buttons that do not look clickable, jargon where plain words would do. The best interfaces feel obvious — and "obvious" is the result of hard design work, not its absence.',
      '## Forms that interrogate',
      'Every form field costs completions. A quote form demanding company size, budget range and "how did you hear about us" is optimising for your CRM at the expense of your pipeline. Ask the minimum — name, contact, message — and gather the rest in conversation.',
      '## Ignoring the phone reality',
      'Most Kenyan web traffic is mobile, yet sites still ship with tap targets designed for mouse cursors, text requiring pinch-zoom, and popups whose close buttons sit off-screen. Test on a real mid-range phone over mobile data — that is your actual median customer, not your office desktop on fibre.',
      '## Hiding the essentials',
      'Delivery costs revealed only at checkout. No phone number anywhere. Missing prices "so they call us" — they do not call; they leave. Trust grows from transparency, and every hidden essential reads as a small warning sign.',
      '## The cheap fix',
      'Watch three real people attempt one key task on your site — buy, book, inquire — without helping them. The first session is usually humbling, and worth more than any redesign meeting.',
    ],
  },
  {
    slug: 'dropshipping-mistakes-beginners-make',
    title: '7 Dropshipping Mistakes That Kill Beginner Stores',
    excerpt:
      'Most failed dropshipping stores die from the same avoidable wounds. Learn them here instead of paying for them.',
    date: '2025-08-24',
    category: 'Dropshipping',
    readTime: 6,
    content: [
      'Having watched many stores launch — my own early attempts included — I can report that beginner failures are remarkably unoriginal. The same seven mistakes account for most of them.',
      '## The fatal seven',
      'One: quitting after the first failed product. Product testing is a numbers game; most tests fail by design, and the business only exists across many attempts. Two: no margin arithmetic. Selling a $10 product for $15 leaves nothing after ads and fees — winners need roughly 3x markup room. Three: ignoring shipping times, then drowning in "where is my order" disputes that were fully predictable at product selection.',
      'Four: launching on a store that looks abandoned — supplier photos, no policies, no about page, broken mobile layout. Trust is the whole game when nobody has heard of you. Five: touching ad campaigns hourly. The algorithm needs days of stable data; panic-editing resets learning and burns the budget twice.',
      'Six: treating customer messages as an annoyance. Slow support converts nervous customers into chargebacks, and chargebacks into payment processor bans — the true store-killer almost nobody warns beginners about. Seven: revenue worship. Screenshots of sales dashboards mean nothing; only margin after ads, fees, refunds and product cost is real.',
      '## The pattern underneath',
      'Every one of these mistakes comes from treating dropshipping as a lottery ticket instead of a retail business. The fix is the same in every case: patience, arithmetic and treating customers like a brand would.',
      'My complete course exists to compress this learning curve — the $500 covers what these mistakes would otherwise charge you many times over.',
    ],
  },
  {
    slug: 'product-photos-that-sell',
    title: 'Product Photos and Videos That Actually Sell',
    excerpt:
      'Customers cannot touch what you sell online — your visuals do all the convincing. How to get scroll-stopping content on any budget.',
    date: '2025-08-17',
    category: 'E-Commerce',
    readTime: 5,
    content: [
      'Online, your product photos are the product. Customers cannot hold it, weigh it or turn it over — every purchase decision runs entirely on what you show them. Yet visuals are where new stores cut corners first.',
      '## The minimum viable photo set',
      'Every product page needs: a clean hero shot on a plain background, lifestyle shots showing the product in real use, a scale reference (in-hand or beside familiar objects — a shocking number of returns are "smaller than expected"), and detail close-ups of texture and quality. Four angles of the same white-background shot is a catalogue, not persuasion.',
      '## Video changed the rules',
      'Short video now outsells photography nearly everywhere it appears — product pages, ads, TikTok, Instagram. The formula is simple and repeatable: show the problem, show the product solving it, show the reaction. Fifteen seconds, phone camera, natural light. Authenticity outperforms production polish so consistently that polished ads now imitate handheld realism.',
      '## Phone-budget quality',
      'A modern phone plus daylight from a window beats an expensive camera under bad light. Shoot near a window, use a plain background (a large sheet of paper works), wipe the lens, and take many shots to choose from. Free editing apps handle brightness and crop — resist heavy filters that misrepresent colour, which converts today and refunds tomorrow.',
      '## For dropshippers specifically',
      'Order your product and shoot your own content. Stores reusing the same supplier images as fifty competitors have no identity; original photos and one honest demo video instantly separate you from the copy-paste crowd — and give your ads creative nobody else is running.',
    ],
  },
  {
    slug: 'instagram-marketing-for-stores',
    title: 'Instagram Marketing for Online Stores: A Working Playbook',
    excerpt:
      'Instagram remains a selling machine for visual products — if you feed it what it currently rewards.',
    date: '2025-08-10',
    category: 'Marketing',
    readTime: 5,
    content: [
      'Instagram remains one of the strongest sales channels for visual products — fashion, beauty, home, accessories — but the platform that rewards you today is not the one from the static-photo era. Here is the current working playbook for stores.',
      '## Reels carry the reach',
      'Instagram distributes Reels to non-followers the way TikTok does, making short video your primary discovery engine. What works for stores: products in use, transformations and before-afters, packing-an-order content, and behind-the-scenes of a real business. Post Reels several times weekly; treat each as a ticket in a reach lottery with surprisingly good odds.',
      '## The profile is a landing page',
      'Assume every new viewer checks your profile before trusting you. Bio stating clearly what you sell and ship ("Nairobi | Countrywide delivery | DM to order"), highlights covering products, reviews and FAQs, and a link that goes somewhere useful. A confused profile leaks every follower your content earns.',
      '## Selling in the DMs',
      'In Kenya especially, Instagram commerce closes in direct messages. Reply fast — minutes, not days — answer price questions directly instead of the trust-killing "DM sent 😊" games, and move serious buyers to WhatsApp for payment and delivery logistics. Saved replies for common questions keep speed sustainable.',
      '## Proof over polish',
      'Repost customer photos and screenshots of happy reviews relentlessly (with permission). Social proof from real buyers converts harder than any studio shoot, and it manufactures itself once you start asking every satisfied customer to tag you.',
    ],
  },
  {
    slug: 'side-hustle-to-real-business',
    title: 'From Side Hustle to Real Business: When and How to Scale',
    excerpt:
      'The habits that grow a side income into a structured business — and the traps that keep hustles small forever.',
    date: '2025-08-03',
    category: 'Business',
    readTime: 6,
    content: [
      'Kenya runs on side hustles — but there is a real difference between income on the side and a business that grows. Having crossed that bridge with MJ Tech Labs, here is what the transition actually involves.',
      '## The mindset shift: systems over effort',
      'A hustle is you selling your hours; a business is a system that produces value with decreasing dependence on your personal heroics. The diagnostic question: if you disappeared for two weeks, what survives? Every process that lives only in your head — pricing, supplier contacts, how you deliver — is a ceiling on growth. Write things down; document as you go. Boring, and transformative.',
      '## Separate the money early',
      'The moment a hustle earns consistently, separate its money from yours: its own M-Pesa line or till, its own account, records of every shilling in and out. Mixed finances hide whether you are actually profitable — many "successful" hustles are quietly subsidised by their owner\'s salary without anyone noticing.',
      '## Formalise when it earns its keep',
      'Registration, KRA compliance and business banking bring costs but unlock the next tier: corporate clients who require invoices and compliance, bank credit, contracts you can enforce. Formalise when opportunities start requiring it — not before the revenue justifies it, not after you have lost deals waiting.',
      '## Reinvest deliberately',
      'The trap is consuming everything the hustle earns; growth needs a reinvestment habit — a fixed percentage back into tools, stock, marketing or skills every month. Compounding works in business exactly as it does in savings: slowly, then suddenly.',
    ],
  },
  {
    slug: 'time-management-for-freelancers',
    title: 'Time Management for Freelancers Juggling Multiple Clients',
    excerpt:
      'Nobody schedules your day but you. The system that keeps deadlines met and evenings free.',
    date: '2025-07-27',
    category: 'Freelancing',
    readTime: 5,
    content: [
      'Freelance freedom has a hidden tax: nobody structures your time for you. Two clients feel easy; four clients with overlapping deadlines will find every weakness in your system — or reveal that you never had one.',
      '## Timebox by client, not by mood',
      'The failure mode is reactive switching — working on whoever emailed most recently. Instead, block days or half-days per project and protect the blocks. Deep work needs runway; the context-switching between codebases can consume a shocking share of a fragmented day. Clients adapt quickly to "I work on your project Tuesdays and Thursdays" — what they cannot adapt to is missed deadlines.',
      '## Manage promises, not just tasks',
      'A freelancer\'s reputation is the gap between what was promised and what was delivered, measured in days. Quote deadlines with buffer built in — everything takes longer than the estimate you made while excited. Deliver early and you are a hero; the same work delivered late makes you a risk. Under-promise deliberately; it is not pessimism, it is engineering.',
      '## Batch the shallow work',
      'Emails, invoices, WhatsApp check-ins and quotes belong in one or two scheduled batches daily — not sprinkled across every hour as they arrive. An inbox checked at 11am and 4pm loses nothing; a developer interrupted every twenty minutes loses the whole day.',
      '## Protect the off switch',
      'Without office hours, work metastasises into every evening. Define an end to the workday and honour it. Burnt-out freelancers miss deadlines, ship bugs and quote badly — rest is not a reward for finishing; it is what makes finishing possible.',
    ],
  },
  {
    slug: 'future-of-web-development',
    title: 'Where Web Development Is Heading: A View From the Trenches',
    excerpt:
      'AI pair programmers, edge computing and the skills that stay valuable no matter what the tooling does next.',
    date: '2025-07-20',
    category: 'AI & Tools',
    readTime: 6,
    content: [
      'Every year someone declares web development dead, and every year the web quietly absorbs its disruptor and grows. Watching the current wave from inside daily practice, here is where things are actually heading — and what it means for anyone building a career.',
      '## AI moves up the stack, and so must we',
      'AI assistants now handle a real share of routine implementation — boilerplate, standard components, first-draft tests. This is not the end of developers; it is a repricing. The valuable work shifts up: understanding problems, designing systems, reviewing and directing machine output, owning quality. The developer who only ever translated tickets into boilerplate is in trouble; the one who can architect and verify is more leveraged than ever.',
      '## The infrastructure quietly standardises',
      'Edge deployment, serverless backends and managed platforms keep absorbing what used to be manual server work. Modern frameworks ship performance patterns — server rendering, streaming, smart bundling — as defaults rather than expertise. The trend line is clear: less time on plumbing, more of the differentiation living in product thinking and domain knowledge.',
      '## What stays valuable',
      'Fundamentals age slowest: HTTP, data modelling, security thinking, debugging discipline, and the ability to read unfamiliar code. Communication compounds — the developer who can explain trade-offs to a non-technical client wins work that pure coders never see. And judgment, the skill of choosing what to build and what to skip, only grows scarcer as generating code gets cheaper.',
      '## For Kenyan developers specifically',
      'Cheaper tools and remote-friendly hiring keep lowering the barriers that once penalised geography. The opportunity has never been wider — for those treating the craft as a career, not a shortcut.',
    ],
  },
];
