import type { Post } from '../posts';

export const posts1: Post[] = [
  {
    slug: 'why-every-kenyan-business-needs-a-website',
    title: 'Why Every Kenyan Business Needs a Website in 2026',
    excerpt:
      'Your customers are already searching online. Here is why a website is no longer optional for Kenyan businesses — and what it actually costs.',
    date: '2026-06-28',
    category: 'Web Development',
    readTime: 5,
    content: [
      'Every week I meet business owners in Nairobi who tell me the same thing: "I get all my customers through referrals and Facebook, why do I need a website?" It is a fair question — and the answer is simpler than most developers make it sound.',
      'A website is your shop that never closes. When someone hears about your business at 9pm and searches your name, what do they find? If the answer is nothing, or a dormant Facebook page from 2023, you just lost the sale to a competitor who took their online presence seriously.',
      '## What a website actually does for you',
      'First, credibility. Kenyan consumers have become cautious — with so many online scams, people verify businesses before sending money. A professional website with your services, location and contact details is the fastest trust signal you can buy.',
      'Second, ownership. Your Facebook page, Instagram account and WhatsApp Business profile all live on platforms you do not control. Accounts get restricted, algorithms change, reach drops. Your website and domain belong to you.',
      'Third, search traffic. Thousands of people search Google every day for services in Kenya — "wedding photographer Nakuru", "accountant Mombasa", "web developer Nairobi". Without a website, you are invisible to all of them.',
      '## What it costs',
      'A clean, professional business website is more affordable than most owners expect, and it pays for itself with a handful of new customers. Start simple: a homepage, services, about and contact page with WhatsApp integration. You can grow from there.',
      'If you are ready to get online, talk to me — I will walk you through exactly what your business needs and what it will cost, with no jargon.',
    ],
  },
  {
    slug: 'nextjs-vs-plain-react',
    title: 'Next.js vs Plain React: Which Should You Choose?',
    excerpt:
      'React is a library, Next.js is a framework built on top of it. Here is how I decide which one to use for client projects.',
    date: '2026-06-21',
    category: 'Web Development',
    readTime: 6,
    content: [
      'One of the most common questions I get from junior developers is whether they should build with plain React (using Vite) or jump straight to Next.js. After shipping projects with both, here is my honest breakdown.',
      '## When plain React is enough',
      'If you are building a dashboard behind a login, an internal tool, or any app where SEO does not matter, plain React with Vite is fantastic. The setup is lighter, the mental model is simpler, and you deploy it as static files anywhere.',
      '## When Next.js wins',
      'The moment your project needs to be found on Google — marketing sites, blogs, e-commerce stores — Next.js becomes the obvious choice. Server-side rendering and static generation mean search engines see full HTML instead of an empty div waiting for JavaScript.',
      'Next.js also gives you file-based routing, image optimisation, and API routes out of the box. For client work, that means less time wiring up infrastructure and more time building features the client actually pays for.',
      '## My rule of thumb',
      'Public-facing and content-driven? Next.js. Internal tool or app behind auth? Either works, pick what your team knows. Learning React for the first time? Learn plain React first so you understand what Next.js is doing for you — then the framework will make sense instead of feeling like magic.',
      'Both are excellent tools. The mistake is not choosing the "wrong" one — it is spending three weeks deciding instead of building.',
    ],
  },
  {
    slug: 'how-i-integrate-mpesa-into-web-apps',
    title: 'How I Integrate M-Pesa Into Web Applications',
    excerpt:
      'STK Push, callbacks, and the gotchas nobody warns you about. A practical overview of adding M-Pesa payments to your app.',
    date: '2026-06-14',
    category: 'Backend',
    readTime: 7,
    content: [
      'M-Pesa integration is one of the most requested features in Kenyan software projects, and for good reason — it is how the country pays. Here is how a typical integration works and the lessons I have learned doing it repeatedly.',
      '## The flow in plain language',
      'The most common integration is STK Push (Lipa na M-Pesa Online). Your app sends a request to Safaricom Daraja API with the customer phone number and amount. The customer gets a payment prompt on their phone, enters their PIN, and Safaricom sends a confirmation to a callback URL on your server.',
      'That callback is where most beginner integrations fall apart. Your server must be reachable on a public HTTPS URL, must respond quickly, and must handle the fact that callbacks can be delayed or occasionally never arrive.',
      '## Lessons from production',
      'Always store the CheckoutRequestID when you initiate payment, and reconcile against it when the callback lands. Build a query-status fallback for when callbacks go missing — it happens more than the documentation suggests. Never mark an order paid based on the frontend saying so; the server-side callback is the only source of truth.',
      'Test in the sandbox thoroughly, but expect surprises in production — sandbox behaviour and live behaviour are not identical, especially around error codes.',
      '## Should you build it yourself?',
      'If you have backend experience, Daraja is well within reach. If not, this is one of those features worth hiring out — payment bugs cost real money and customer trust. It is a core part of what I build for clients, from e-commerce checkouts to subscription billing.',
    ],
  },
  {
    slug: 'freelancing-in-kenya-getting-your-first-clients',
    title: 'Freelancing in Kenya: How I Got My First Clients',
    excerpt:
      'No connections, no portfolio, no problem. The practical steps that took me from zero clients to a full pipeline.',
    date: '2026-06-07',
    category: 'Freelancing',
    readTime: 6,
    content: [
      'When I started freelancing five years ago, I had no portfolio, no network and no idea where clients came from. Here is what actually worked, in the order it worked.',
      '## Start closer than you think',
      'My first paying projects came from my immediate circle — a relative\'s business that needed a website, a friend\'s church that wanted an events page. These projects paid little, but they gave me two things money cannot buy at that stage: real deployed work I could show, and referrals.',
      'Kenyan business runs on referrals. One happy client telling their circle about you is worth more than a hundred cold emails. Treat every small project like it is your biggest one.',
      '## Build in public',
      'I started posting what I was building on X and LinkedIn — screenshots, small wins, before-and-after shots of client sites. Within months, inquiries started coming from people I had never met. You do not need to go viral; you need to be findable and visibly competent.',
      '## The platforms question',
      'Upwork and Fiverr can work, but competing globally on price is brutal when you are starting. I found better results targeting local businesses directly — they pay in M-Pesa, they prefer working with someone who understands their market, and the competition is thinner than on international platforms.',
      '## What I would tell my younger self',
      'Charge more than feels comfortable. Deliver slightly more than promised. Reply fast — in this market, responsiveness alone puts you ahead of half the competition. And build your own website; it is your best salesperson.',
    ],
  },
  {
    slug: 'dropshipping-101-what-it-is-and-how-it-works',
    title: 'Dropshipping 101: What It Is and How It Actually Works',
    excerpt:
      'The honest beginner\'s guide — what dropshipping is, how the money flows, and whether it still works in 2026.',
    date: '2026-05-31',
    category: 'Dropshipping',
    readTime: 6,
    content: [
      'Dropshipping gets described as either a get-rich-quick scheme or a dead business model, depending on who you ask. The truth is in the middle: it is a real retail model with real margins, and it rewards people who treat it like a business.',
      '## The model in one paragraph',
      'You run an online store, but you hold no inventory. When a customer orders from your store, you purchase the item from a supplier who ships it directly to the customer. Your profit is the difference between your retail price and the supplier cost, minus advertising and fees.',
      '## Why people love it',
      'Low startup capital — no warehouse, no bulk stock purchases, no unsold inventory gathering dust. You can test products quickly: if something does not sell, you simply stop advertising it. Nothing is wasted except the ad spend used to test.',
      '## Why people fail at it',
      'Most beginners fail for predictable reasons: picking saturated products, ignoring shipping times, treating customer service as optional, and giving up after one failed product test. Successful dropshippers expect most product tests to fail — the business is finding the few that win and scaling them hard.',
      '## Does it still work in 2026?',
      'Yes, but the bar is higher. Customers expect decent shipping times, real branding and responsive support. The "ugly store, random gadget, 30-day shipping" era is over. What works now is closer to building a real brand — which is exactly what I teach in my complete dropshipping course. If you want the full roadmap from zero to first sale, check the Services page or message me on WhatsApp.',
    ],
  },
  {
    slug: 'choosing-winning-dropshipping-products',
    title: 'How to Choose Winning Dropshipping Products',
    excerpt:
      'Product selection makes or breaks a dropshipping store. Here is the framework I use to evaluate any product before spending a shilling on ads.',
    date: '2026-05-24',
    category: 'Dropshipping',
    readTime: 7,
    content: [
      'Ask any experienced dropshipper what matters most and you will hear the same answer: the product. Great marketing cannot save a product nobody wants. Here is the framework I use and teach.',
      '## The problem-first filter',
      'The best products solve a visible, annoying problem or trigger a strong emotional response within three seconds of seeing them. Scroll-stopping matters because your customer discovers products on TikTok and Instagram, not by searching. Ask: can a 15-second video make a stranger want this?',
      '## The numbers that matter',
      'I look for products I can sell at roughly three times the supplier cost. That margin has to cover advertising, payment fees, refunds and still leave profit. A product with thin margins punishes every mistake; a product with 3x margins forgives your learning curve.',
      'Price point matters too. Items retailing between $20 and $60 hit the sweet spot — cheap enough for an impulse purchase, expensive enough that each sale meaningfully covers ad costs.',
      '## Validation before scaling',
      'Check whether the product is already selling: look at ad libraries for active campaigns, check engagement on product videos, and study competitor stores. Existing demand is a feature, not a bug — it proves the market. Your edge comes from a better angle, better creative or better branding, not from finding a product nobody has ever seen.',
      '## Red flags to avoid',
      'Fragile items that break in shipping, products with sizing (returns will eat you alive), anything with batteries or liquids that complicates shipping, and trademarked or patented designs. Boring reliability beats exciting risk when you are starting.',
      'Product research is the first module of my dropshipping course — because everything else is built on getting this right.',
    ],
  },
  {
    slug: 'is-typescript-worth-it',
    title: 'Is TypeScript Worth It? My Answer After Years of Using It',
    excerpt:
      'TypeScript adds friction upfront and saves you from disasters later. Here is when the trade is worth making.',
    date: '2026-05-17',
    category: 'JavaScript',
    readTime: 5,
    content: [
      'I resisted TypeScript for my first two years as a developer. It felt like bureaucracy — writing types instead of shipping features. Then I inherited a large JavaScript codebase, spent a week hunting a bug that TypeScript would have caught at compile time, and never looked back.',
      '## What TypeScript actually buys you',
      'The obvious win is catching errors before runtime — passing the wrong argument, accessing a property that does not exist, forgetting a null check. But the bigger win is confidence when changing code. In a typed codebase, renaming a function or changing a data shape shows you every place that breaks, instantly.',
      'The underrated win is documentation. Types tell the next developer (usually future you) exactly what a function expects and returns, and unlike comments, types cannot go stale — the compiler enforces them.',
      '## The honest costs',
      'There is a learning curve, especially around generics and utility types. Setup adds complexity. And you will occasionally fight the compiler over code you know is correct. Small scripts and quick prototypes genuinely do not need it.',
      '## My verdict',
      'For anything that will live longer than a month or be touched by more than one person, TypeScript pays for itself many times over. Every serious project I ship for clients is TypeScript by default. Start loose — enable it with permissive settings, type the important boundaries, and tighten as you learn. You do not have to be a type wizard on day one.',
    ],
  },
  {
    slug: 'rest-vs-graphql-choosing-an-api-style',
    title: 'REST vs GraphQL: Choosing the Right API Style',
    excerpt:
      'Both are proven ways to build APIs. The right choice depends on your data, your clients and your team — not on hype.',
    date: '2026-05-10',
    category: 'Backend',
    readTime: 6,
    content: [
      'Every few months a client or student asks me whether they should build their API with REST or GraphQL, usually because they read that one of them is "dead". Neither is dead. They solve different problems.',
      '## Where REST shines',
      'REST is simple, universally understood, and caches beautifully. Every developer, tool and HTTP proxy on earth knows what GET /products/42 means. For most CRUD applications — which is most applications — REST endpoints are faster to build, easier to debug and easier to secure.',
      '## Where GraphQL shines',
      'GraphQL earns its complexity when many different clients need different slices of the same data. A mobile app that needs light payloads, a dashboard that needs deep nested data, a partner integration that needs something else — one GraphQL schema serves all three without you writing a new endpoint for each view.',
      'It also eliminates the classic mobile problem of making five API calls to render one screen. One query, exactly the fields you need, nothing more.',
      '## The practical decision',
      'If you have one frontend and a straightforward data model, use REST and move on with your life. If you have multiple clients with genuinely different data needs, or your frontend team is constantly waiting on backend endpoint changes, GraphQL starts paying for its complexity.',
      'For most Kenyan startups and business projects I build, well-designed REST with clear documentation wins on simplicity and hiring. Choose boring technology until you have a problem boring technology cannot solve.',
    ],
  },
  {
    slug: 'react-native-vs-flutter-2026',
    title: 'React Native vs Flutter: What I Recommend in 2026',
    excerpt:
      'Both frameworks build excellent cross-platform apps. Here is how I choose between them for client projects.',
    date: '2026-05-03',
    category: 'Mobile',
    readTime: 6,
    content: [
      'When a client asks for a mobile app, the first technical decision is the framework. Building separate native apps for Android and iOS doubles the cost, so cross-platform is the default for most budgets. That leaves two serious options: React Native and Flutter.',
      '## The case for React Native',
      'If your team already knows React — and most web teams do — React Native lets you reuse that knowledge, and sometimes actual code, across web and mobile. The ecosystem is massive, hiring is easier, and Expo has made the development experience genuinely pleasant, handling builds, updates and native modules that used to be painful.',
      '## The case for Flutter',
      'Flutter renders its own UI, which means your app looks identical on every device and Android version — a real advantage in markets like Kenya where older Android devices are common. Performance is consistently smooth, and Dart is a clean language that developers pick up quickly.',
      '## How I actually decide',
      'Team background first: React shop → React Native; fresh team or heavy custom UI → Flutter. App type second: content and forms apps suit either; animation-heavy or highly branded UIs lean Flutter; apps sharing logic with a React web app lean React Native.',
      'Both are mature, both power apps with millions of users, and both will serve a typical business app well. The framework matters less than the developer building with it — architecture, offline handling and attention to the details users feel are what separate good apps from abandoned ones.',
    ],
  },
  {
    slug: 'why-website-speed-matters',
    title: 'Why Website Speed Matters More Than You Think',
    excerpt:
      'Slow websites lose customers silently. Here is what speed costs you and the fixes that deliver the biggest wins.',
    date: '2026-04-26',
    category: 'Web Development',
    readTime: 5,
    content: [
      'Nobody complains about a slow website — they just leave. That is what makes performance such a silent killer for businesses: you never hear from the customers you lost.',
      '## The stakes',
      'Research consistently shows that as load time climbs from one second toward five, bounce rates jump dramatically. In Kenya this matters double: many of your visitors are on mid-range phones with variable mobile data. A site that feels instant on your office WiFi can be unusable on 3G in a rural county.',
      'Google also uses page speed as a ranking signal. A slow site does not just convert worse — it gets seen less in the first place.',
      '## Where the biggest wins are',
      'Images are the number one offender on almost every slow site I audit. Serving properly sized, compressed, modern-format images regularly cuts page weight by more than half — no other single fix comes close.',
      'After images: eliminate unused JavaScript and bloated plugins, enable caching and compression on your server, and use a CDN so your content is served from close to your visitors. If you are on WordPress, ruthlessly audit your plugins — each one is a potential performance tax.',
      '## How to check where you stand',
      'Run your site through PageSpeed Insights and test it on a real phone using mobile data, not just your laptop. If your homepage takes more than about three seconds to become usable on a phone, you are losing people.',
      'Every site I build ships fast by default — performance is a feature, not an afterthought.',
    ],
  },
  {
    slug: 'seo-basics-small-business',
    title: 'SEO Basics Every Small Business Should Know',
    excerpt:
      'You do not need an agency retainer to rank on Google. These fundamentals get most small businesses 80% of the way.',
    date: '2026-04-19',
    category: 'Marketing',
    readTime: 6,
    content: [
      'SEO has a reputation for being mysterious and expensive. For small businesses, most of the value comes from unglamorous fundamentals that anyone can implement.',
      '## Start with Google Business Profile',
      'For local businesses, the free Google Business Profile is the highest-return SEO action available. Complete every field, add real photos, choose accurate categories, and gather reviews consistently. When someone searches "salon near me" or "hardware Eldoret", that profile is what competes.',
      '## Match the words your customers use',
      'Your pages should use the language customers actually type into Google. If people search "cheap website design Nairobi" and your site only says "bespoke digital experiences", Google has nothing to match. Write a page for each service you offer, in plain language, naming the locations you serve.',
      '## The technical basics',
      'Make sure your site loads fast, works properly on phones, and uses HTTPS. Give every page a descriptive title and meta description. These are table stakes — without them, everything else underperforms.',
      '## Content earns rankings over time',
      'A blog that genuinely answers customer questions — prices, comparisons, how-tos, common mistakes — accumulates search traffic month after month. One good article answering "how much does a website cost in Kenya" can bring in leads for years.',
      '## What to ignore',
      'Anyone promising "#1 on Google in 7 days", bulk backlink packages, and keyword-stuffed text written for robots. These range from useless to actively harmful.',
      'SEO is compound interest: small, consistent, correct actions that stack up. Start now and be patient.',
    ],
  },
  {
    slug: 'how-to-price-freelance-projects',
    title: 'How to Price Freelance Projects Without Undercharging',
    excerpt:
      'Most freelancers undercharge for years. Here is the pricing approach that fixed it for me.',
    date: '2026-04-12',
    category: 'Freelancing',
    readTime: 6,
    content: [
      'The most expensive mistake of my early freelance career was not a bad project — it was systematic underpricing. If you consistently win every quote you send, your prices are too low.',
      '## Price the value, not your hours',
      'Clients do not buy your hours; they buy outcomes. A booking system that saves a business ten hours of admin every week is worth a lot more than the time it takes you to build it. Anchor your price to what the solution is worth to their business, and your hours become irrelevant to the conversation.',
      '## Scope is everything',
      'Vague scope is how projects die. Before quoting, define exactly what is included: number of pages or screens, features, revision rounds, and what counts as "done". Then add the sentence that saves every freelancer: anything outside this scope is quoted separately.',
      'Deposits are non-negotiable — I take a percentage upfront before any work begins. A client who resists a deposit is showing you how the final invoice conversation will go.',
      '## Practical rules that served me well',
      'Quote a range in the first conversation to filter mismatched budgets early. Raise your rates with every two or three projects until you start losing some quotes — that is the market telling you where you belong. And never lower your price without removing scope; discounting the same work teaches clients your prices are fiction.',
      '## The mindset shift',
      'Charging properly is not greed — it is what funds the reliability, quality and responsiveness clients actually want. An underpaid freelancer juggling eight projects serves everyone badly. Charge enough to do great work for fewer clients.',
    ],
  },
  {
    slug: 'postgresql-vs-mongodb',
    title: 'PostgreSQL vs MongoDB: Picking the Right Database',
    excerpt:
      'Relational or document database? The honest answer for most projects, and the cases where each one truly wins.',
    date: '2026-04-05',
    category: 'Backend',
    readTime: 6,
    content: [
      'Database choice generates endless debate, but for typical web applications the decision is simpler than the internet makes it seem.',
      '## The default answer',
      'For most applications — e-commerce, SaaS, bookings, anything with users, orders and payments — PostgreSQL is the right default. The data in these systems is naturally relational: users have orders, orders have items, items have products. A relational database enforces those relationships so bugs cannot silently corrupt your data.',
      'Postgres also handles the "flexible" cases people think they need MongoDB for: its JSONB columns store schemaless documents inside a relational database, giving you both worlds in one system.',
      '## Where MongoDB genuinely fits',
      'MongoDB shines when your data really is document-shaped and self-contained — content management payloads, event logs, product catalogues where every item has wildly different attributes. Its horizontal scaling story is also mature for genuinely massive write loads, though very few projects ever reach that scale.',
      '## The mistake to avoid',
      'The classic error is choosing MongoDB because "schemas slow us down", then spending years rebuilding relational integrity in application code — checking references manually, handling orphaned records, writing migration scripts for inconsistent documents. Schema design is not friction; it is the thinking that saves you later.',
      '## Bottom line',
      'Reach for Postgres by default. Reach for MongoDB when your data model is genuinely document-oriented and you understand the trade-offs. And whichever you choose, learn to design data properly — a well-modelled database outlives every framework trend sitting on top of it.',
    ],
  },
  {
    slug: 'shopify-vs-custom-ecommerce',
    title: 'Shopify vs Custom Store: Where Should You Sell?',
    excerpt:
      'Platform convenience or full control? How to choose the right foundation for your online store.',
    date: '2026-03-29',
    category: 'E-Commerce',
    readTime: 6,
    content: [
      'When someone decides to sell online, the first fork in the road is platform versus custom build. I build both for clients, so here is the unbiased version.',
      '## The case for Shopify',
      'Shopify\'s pitch is speed and reliability: a professional store live in days, hosting and security handled, hundreds of apps for everything from reviews to upsells. For dropshipping especially, the ecosystem of product-sourcing and fulfilment integrations is unmatched — it is what I recommend to most of my course students for their first store.',
      'The costs are the monthly subscription, transaction fees, and the ceiling: you customise within Shopify\'s boundaries. For 90% of stores, that ceiling is far above anything they will ever need.',
      '## The case for a custom store',
      'A custom build (Next.js frontend, your choice of backend) makes sense when your requirements genuinely do not fit a platform: unusual checkout flows, deep M-Pesa integration beyond what plugins offer, marketplace features, subscription logic, or when platform fees at high volume exceed the cost of ownership.',
      'You get total control and no monthly platform tax — in exchange for build cost, maintenance responsibility and slower iteration on standard e-commerce features that platforms give you free.',
      '## My honest recommendation',
      'Start on a platform if you are validating a business. Move custom when you have revenue and a specific limitation blocking growth — not before. The worst outcome is spending months and serious money on a custom store for a business idea you have not yet proven. Validate cheap, then invest.',
    ],
  },
  {
    slug: 'facebook-ads-for-dropshipping',
    title: 'Facebook Ads for Dropshipping: A Beginner\'s Framework',
    excerpt:
      'How to structure your first campaigns, what budget to expect, and the metrics that actually matter.',
    date: '2026-03-22',
    category: 'Dropshipping',
    readTime: 7,
    content: [
      'Facebook (Meta) ads remain a core traffic engine for dropshipping. They are also where beginners burn most of their money. Here is the framework I teach to make that learning curve cheaper.',
      '## Creative is the targeting now',
      'Modern Meta campaigns work best with broad targeting and strong creative. The algorithm finds your buyers — your job is giving it ad creative that makes the right people stop scrolling. Short video that shows the product solving its problem in the first three seconds outperforms almost everything else.',
      'Make multiple variations: different hooks, different angles, different first frames. You are not testing the product once; you are testing angles until one connects.',
      '## Structure and budget',
      'Start simple: one campaign, broad audience, several ad variations, modest daily budget. Resist the urge to touch anything for the first few days — the algorithm needs data to optimise, and constant edits reset its learning.',
      'Expect your first products to lose money. That is not failure; that is tuition. The budget you need is not for one test — it is for enough tests to find a winner. This is where most beginners are undercapitalised in expectations, not in cash.',
      '## The metrics that matter',
      'Watch cost per purchase against your product margin — that is the whole business in one comparison. Click-through rate tells you if the creative hooks; conversion rate on the store tells you if the product page sells. Diagnose in that order: no clicks means creative problem, clicks but no sales means page or offer problem.',
      'Paid traffic is a skill, and skills are learnable. My dropshipping course covers campaign setup click by click, including the scaling playbook for when you find a winner.',
    ],
  },
  {
    slug: 'tiktok-marketing-ecommerce',
    title: 'TikTok Marketing for E-Commerce: Organic and Paid',
    excerpt:
      'TikTok can send startling amounts of free traffic to a store — if you understand what the platform rewards.',
    date: '2026-03-15',
    category: 'Marketing',
    readTime: 6,
    content: [
      'TikTok changed e-commerce marketing by making it possible for a brand-new store with zero followers to reach millions of viewers. The catch: the platform has strong opinions about what content deserves that reach.',
      '## What TikTok rewards',
      'TikTok distributes content based on watch time and engagement, not follower count. Every video gets tested on a small audience; hold their attention and it gets shown to more. This means the first two seconds of your video decide everything — lead with the most interesting moment, never with a logo or slow intro.',
      'For product content, the formats that consistently work are: the product solving a problem on camera, honest demonstration with real reactions, before-and-after reveals, and "things you didn\'t know you needed" style discovery content.',
      '## Organic strategy for stores',
      'Post consistently — multiple times per week minimum — because each video is a fresh lottery ticket with better odds than people think. Do not delete videos that flop; volume and iteration are the strategy. Study which of your videos held attention and make more like those.',
      '## Paid on TikTok',
      'TikTok ads work best when they do not look like ads. Reuse your best-performing organic style in paid campaigns rather than producing polished commercials. The audience skews younger and impulse purchases under $50 perform especially well.',
      'For Kenyan sellers, TikTok\'s local growth has been explosive — the audience is there, and the brands winning attention are the ones treating TikTok as its own craft rather than a place to repost Instagram content.',
    ],
  },
  {
    slug: 'docker-for-beginners',
    title: 'Docker for Beginners: Why "It Works on My Machine" Dies Here',
    excerpt:
      'Containers solve one of software\'s oldest problems. Here is what Docker actually does, explained without jargon.',
    date: '2026-03-08',
    category: 'DevOps',
    readTime: 6,
    content: [
      'Every developer eventually lives this story: the app runs perfectly on your laptop, then breaks on the server — different OS, different Node version, missing dependency, mystery config. Docker exists to kill this entire category of problem.',
      '## The core idea',
      'A container packages your application together with everything it needs to run — runtime, libraries, system tools, configuration — into a single unit that runs identically anywhere Docker runs. Your laptop, a teammate\'s Windows machine, a cloud server: same container, same behaviour.',
      'Unlike a virtual machine, a container does not bundle a whole operating system. Containers share the host\'s kernel, which makes them start in seconds and run with minimal overhead — you can run dozens on a modest server.',
      '## The three words that matter',
      'A Dockerfile is the recipe: instructions for assembling your app and its environment. An image is the packaged result of that recipe — a frozen, shareable snapshot. A container is a running instance of an image. Recipe, cake, slice being eaten.',
      '## Why it matters for your career',
      'Beyond consistency, Docker unlocks the modern deployment world: CI/CD pipelines build and ship images, cloud platforms run them, and tools like docker-compose let you spin up your whole stack — app, database, cache — with one command on any machine.',
      'Start small: containerise one Node or Python app, run it locally, and push the image to a registry. That single exercise teaches most of what you will use day to day.',
    ],
  },
];
